[package]
name = "uz"
version = "0.0.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
utils = { path = "crates/utils" }

[dev-dependencies]
pollster = "0.4.0"

[dependencies]
